### ISSUE TITLE
Add `update_global_adjustment_frequency()`

### ISSUE THREAD

**Issue by ghost** [setheum/setheum#322]
Add `update_global_adjustment_frequency()` that updates the global `SerpTesSchedule`  globally for the SERP-TES in a storagemap.

And put the param under the governance of the `MonetaryCouncil`

**Comment by balqaasem** [comment]
And how about updating `currency_adjustment_frequency` for specific currencies, where every settcurrency can be governed to have a certain adjustment frequency and the `MonetaryCouncil` can just use `update_currency_adjustment_frequency(currency_id)` to update.

**Comment by balqaasem** [comment]
And we can also support this at the same time.
Such that both the global and and currency-specific params can be updated. 

So, how do we make sure there is no conflicts between these two params affecting the currencies?

**Comment by ghost** [comment]
I guess we are using blocktime right?

**Comment by ghost** [comment]
As most of our modules use blocktime... Or are we using timestamp?

**Comment by balqaasem** [comment]
We will use timestamp.  Check #340 for the ref

**Comment by balqaasem** [comment]
> And we can also support this at the same time.
> Such that both the global and and currency-specific params can be updated.
> 
> So, how do we make sure there is no conflicts between these two params affecting the currencies?

So, for this... I think we should exclusively just use `global-specific-params`. This also lets us have different types of auctions at the same time, therefore eliminating huge pricing risks for both the serp and the bidders, because we could have a bid that cancels out another and we could even have a bid that just appears out of nowhere to make other bids a loss for either the system or the bidders. Therefore, we will just go with the global-params.
Alhamdulillah!

**Comment by balqaasem** [comment]
Is not needed, close
